### PR TITLE
Cldfbench

### PR DESCRIPTION
**Pull request by xrotwang**

### CODE REVIEW

**Review by xrotwang — COMMENTED** [review]
@johenglisch Do we know, why the `Homonym` column is not included in the new CLDF here: https://github.com/dictionaria/palula/pull/1/files?diff=split&w=1#diff-71461c25688b8e8d07a1270715035d32b5e00ae2d9ecc06014a9cfbf21c4a987
?

**Comment by johenglisch** [comment]
> @johenglisch Do we know, why the `Homonym` column is not included in the new CLDF here: https://github.com/dictionaria/palula/pull/1/files?diff=split&w=1#diff-71461c25688b8e8d07a1270715035d32b5e00ae2d9ecc06014a9cfbf21c4a987
> ?

Hm, I don't know why the homonym number was in there to begin with -- it's mentioned neither in the `md.json` nor in `pydictionaria`'s default values…

We could add it to the `md.json` but that would make this the only submission that includes the original `\hm` markers from the SFM input, as far as I can tell.

**Comment by johenglisch** [comment]
Okay, `\hm` → `Homonym` used to be part of `pydictionaria`'s defaults but got removed at some point.  So this column was just an artifact from way back when.

**Comment by xrotwang** [comment]
It's a bit difficult, to assess the impact on the CLDF data when all rows have changed. But I guess all of this can be explained. `examples.csv` doesn't have media IDs, because there's no media for Palula, etc.

**Comment by xrotwang** [comment]
I think we can merge this, as soon as loading the production db from this CLDF is implemented.

**Pull request merged**
